import { LegalPageLayout } from '@/components/LegalPageLayout';

const TermsOfService = () => {
  return (
    <LegalPageLayout title="Terms of Service">
      <section>
        <h2 className="text-xl font-semibold mb-3">1. About This Platform and the Operator</h2>
        <p className="text-muted-foreground">DM.me ("Platform", "we", "us", "our") is a creator monetization platform that allows content creators ("Creators") to receive paid messages from their audience ("Fans"). The Platform is owned and operated by Nextchapter AI For Online Selling, a Commercial Sole Proprietorship Establishment registered in Dubai, UAE (Trade License No. 1610274, Registration No. 2827558), with its registered address at Future Tower, Business Bay, Dubai, United Arab Emirates.</p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-3">2. Acceptance of Terms</h2>
        <p className="text-muted-foreground">By creating an account, accessing, or using the Platform, you confirm that you have read, understood, and agree to be bound by these Terms of Service ("Terms") and all policies incorporated by reference, including our Privacy Policy, Refund Policy, Cookie Policy, and Acceptable Use Policy. If you do not agree, you must not use the Platform.</p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-3">3. Eligibility</h2>
        <p className="text-muted-foreground mb-3">You must be at least 18 years of age to use this Platform in any capacity. By registering, you represent and warrant that:</p>
        <ul className="list-disc list-inside space-y-1 text-muted-foreground">
          <li>You are at least 18 years old;</li>
          <li>You are not prohibited from using our services under the laws of your country of residence;</li>
          <li>You will provide accurate, complete, and current registration information;</li>
          <li>You are not a person previously suspended or removed from the Platform.</li>
        </ul>
        <p className="text-muted-foreground mt-3">We may request identity and age verification documents at any time. Failure to comply may result in account suspension.</p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-3">4. AI-Assisted Messaging — Important Disclosure</h2>
        <p className="text-muted-foreground mb-3 font-medium">This section is critical. Read it carefully before using the Platform.</p>
        <p className="text-muted-foreground mb-3">DM.me is a platform where Creators configure an AI persona — a digital assistant trained to respond in their voice and style — that may reply to Fan messages on their behalf. This means:</p>
        <ul className="list-disc list-inside space-y-1 text-muted-foreground mb-3">
          <li>Messages you receive as a Fan may be generated by an artificial intelligence system, not written in real time by the Creator personally.</li>
          <li>The AI persona is set up, trained, and approved by the Creator.</li>
          <li>Replies reflect the Creator's chosen style, personality, and content guidelines.</li>
          <li>A disclosure notice ("Replies may be AI-assisted") is displayed in the messaging interface.</li>
          <li>Creators remain responsible for all content produced by their AI persona.</li>
        </ul>
        <p className="text-muted-foreground">By using the Platform as a Fan, you acknowledge and accept that AI-assisted responses are a core feature of the service. Payment for messages is for access to the Creator's exclusive content channel, not a guarantee that any specific reply is written personally by the Creator.</p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-3">5. Account Registration</h2>
        <p className="text-muted-foreground mb-3">To use the Platform, you must register an account and provide a valid email address, a secure password, and any additional information required during onboarding. You are solely responsible for maintaining the confidentiality of your account credentials and for all activity occurring under your account. You must notify us immediately at <a href="mailto:support@dm-me.io" className="text-primary hover:underline">support@dm-me.io</a> if you suspect unauthorised access.</p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-3">6. Creator Accounts</h2>
        <p className="text-muted-foreground mb-3">By registering as a Creator, you agree to:</p>
        <ul className="list-disc list-inside space-y-1 text-muted-foreground mb-3">
          <li>Submit to identity verification as required;</li>
          <li>Provide accurate payment/payout information;</li>
          <li>Comply with all applicable laws in your jurisdiction;</li>
          <li>Ensure all content you upload or that your AI persona produces complies with our Acceptable Use Policy;</li>
          <li>Own or have full rights to all content uploaded to the Platform;</li>
          <li>Not misrepresent yourself or create false impressions about your identity.</li>
        </ul>
        <p className="text-muted-foreground">Creator accounts are subject to approval. We reserve the right to refuse or revoke Creator status at our sole discretion.</p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-3">7. Platform Fees and Creator Payouts</h2>
        <ul className="list-disc list-inside space-y-2 text-muted-foreground">
          <li>The Platform charges a service fee of <strong>25%</strong> on all Creator earnings. The Creator receives 75% of the message revenue they generate.</li>
          <li>Payment processing fees charged by Stripe are absorbed by the Platform and are not deducted from Fan wallets or Creator earnings.</li>
          <li>Creators may request payouts weekly. A minimum payout threshold of USD 25 applies.</li>
          <li>Payouts are processed via Stripe and typically arrive within 2–5 business days.</li>
          <li>Creators are solely responsible for any taxes applicable to their earnings in their jurisdiction.</li>
        </ul>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-3">8. Fan Wallet and Payments</h2>
        <ul className="list-disc list-inside space-y-1 text-muted-foreground">
          <li>Fans purchase credits to fund a wallet on the Platform.</li>
          <li>Credits are used to send paid messages to Creators at per-message rates set by the Creator.</li>
          <li>Wallet credits are purchased in USD via Stripe. Credits do not expire.</li>
          <li>Credits are non-refundable except as set out in our <a href="/refund-policy" className="text-primary hover:underline">Refund Policy</a>.</li>
          <li>The Platform does not guarantee a response time or a personal (non-AI) response.</li>
          <li>All payments are processed securely by Stripe. We do not store your full card details.</li>
        </ul>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-3">9. Prohibited Content and Conduct</h2>
        <p className="text-muted-foreground mb-3">You may not use the Platform to:</p>
        <ul className="list-disc list-inside space-y-1 text-muted-foreground">
          <li>Post, transmit, or solicit content depicting or describing minors in a sexual context;</li>
          <li>Post explicit sexual content including visible genitalia or sex acts;</li>
          <li>Harass, threaten, bully, or intimidate other users;</li>
          <li>Impersonate another person or entity;</li>
          <li>Infringe any third-party intellectual property rights;</li>
          <li>Upload malware, viruses, or harmful code;</li>
          <li>Engage in fraud, chargebacks abuse, or deceptive practices;</li>
          <li>Violate any applicable law or regulation.</li>
        </ul>
        <p className="text-muted-foreground mt-3">See our <a href="/acceptable-use" className="text-primary hover:underline">Acceptable Use Policy</a> for the full content standards.</p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-3">10. Intellectual Property</h2>
        <p className="text-muted-foreground">You retain ownership of content you create and upload. By posting content on the Platform, you grant us a worldwide, non-exclusive, royalty-free licence to host, store, display, and distribute your content solely as necessary to operate the Platform. The Platform name, logo, branding, and all Platform software are owned by or licensed to Nextchapter AI For Online Selling. You may not use these without our express written permission.</p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-3">11. DMCA and Copyright</h2>
        <p className="text-muted-foreground">We respect intellectual property rights. If you believe content on the Platform infringes your copyright, submit a DMCA notice to: <a href="mailto:dmca@dm-me.io" className="text-primary hover:underline">dmca@dm-me.io</a>. Repeat infringers will have their accounts terminated. See our <a href="/dmca" className="text-primary hover:underline">DMCA Policy</a> for full notice requirements.</p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-3">12. Account Termination</h2>
        <p className="text-muted-foreground mb-3">We may suspend or permanently terminate your account, with or without notice, if you:</p>
        <ul className="list-disc list-inside space-y-1 text-muted-foreground">
          <li>Violate these Terms or any incorporated policy;</li>
          <li>Post prohibited content;</li>
          <li>Engage in fraudulent or abusive behaviour;</li>
          <li>Fail to provide identity verification when required;</li>
          <li>Generate excessive chargebacks or payment disputes.</li>
        </ul>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-3">13. Disclaimer of Warranties</h2>
        <p className="text-muted-foreground uppercase text-sm">The platform is provided "as is" and "as available" without warranties of any kind, express or implied, including warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that the platform will be uninterrupted, error-free, or free of viruses.</p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-3">14. Limitation of Liability</h2>
        <p className="text-muted-foreground uppercase text-sm">To the maximum extent permitted by applicable law, Nextchapter AI For Online Selling shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the platform. Our total liability to you for any claim shall not exceed the greater of (a) USD 100 or (b) the amount you paid to us in the 12 months preceding the claim.</p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-3">15. Indemnification</h2>
        <p className="text-muted-foreground">You agree to indemnify, defend, and hold harmless Nextchapter AI For Online Selling, its owners, employees, and agents from any claims, damages, losses, and costs (including legal fees) arising from your use of the Platform, your content, your AI persona's content, or your violation of these Terms.</p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-3">16. Governing Law and Dispute Resolution</h2>
        <p className="text-muted-foreground">These Terms are governed by the laws of Dubai, United Arab Emirates. Any dispute arising from or relating to these Terms or the Platform shall be subject to the exclusive jurisdiction of the courts of Dubai, United Arab Emirates.</p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-3">17. Changes to These Terms</h2>
        <p className="text-muted-foreground">We may update these Terms at any time. We will notify you of material changes by email or by posting a notice on the Platform. Your continued use of the Platform after the effective date of updated Terms constitutes your acceptance.</p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-3">18. Contact</h2>
        <p className="text-muted-foreground">For questions about these Terms: <a href="mailto:legal@dm-me.io" className="text-primary hover:underline">legal@dm-me.io</a><br />For general support: <a href="mailto:support@dm-me.io" className="text-primary hover:underline">support@dm-me.io</a></p>
      </section>
    </LegalPageLayout>
  );
};

export default TermsOfService;
